CREATE DATABASE IF NOT EXISTS company;
USE company;

CREATE USER IF NOT EXISTS 'webuser'@'%' IDENTIFIED BY 'web321';
GRANT ALL PRIVILEGES ON company.* TO 'webuser'@'%';
FLUSH PRIVILEGES;

CREATE TABLE employees (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    salary INT(10) NOT NULL
);

